-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

SET SERVEROUTPUT ON

DECLARE
	v_count 					NUMBER := 0;
	v_sequence_departamento		VARCHAR2(50) := 'SEQUENCE_DEPARTAMENTO';
	v_sequence_projeto			VARCHAR2(50) := 'SEQUENCE_PROJETO';
	v_sequence_empregado		VARCHAR2(50) := 'SEQUENCE_EMPREGADO';
	v_sequence_acessoria		VARCHAR2(50) := 'SEQUENCE_ACESSORIA';
	v_sequence_cliente			VARCHAR2(50) := 'SEQUENCE_CLIENTE';
	v_table_departamento		VARCHAR2(50) := 'DEPARTAMENTO';
	v_table_projeto				VARCHAR2(50) := 'PROJETO';
	v_table_empregado			VARCHAR2(50) := 'EMPREGADO';
	v_table_acessoria			VARCHAR2(50) := 'ACESSORIA';
	v_table_endereco			VARCHAR2(50) := 'ENDERECO';
	v_table_cliente				VARCHAR2(50) := 'CLIENTE';
	v_owner						VARCHAR2(50) := 'PIS';
	
BEGIN
	
	SELECT COUNT(*) 
		INTO v_count
			FROM USER_SEQUENCES WHERE SEQUENCE_NAME = v_sequence_departamento;
	
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE ' || v_sequence_departamento;
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_departamento || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_departamento || ' NAO EXISTE.');
	END IF;	
	
	SELECT COUNT(*) 
		INTO v_count
			FROM USER_SEQUENCES WHERE SEQUENCE_NAME = v_sequence_projeto;
	
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE ' || v_sequence_projeto;
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_projeto || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_projeto || ' NAO EXISTE.');
	END IF;	
	
	SELECT COUNT(*) 
		INTO v_count
			FROM USER_SEQUENCES WHERE SEQUENCE_NAME = v_sequence_empregado;
	
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE ' || v_sequence_empregado;
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_empregado || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_empregado || ' NAO EXISTE.');
	END IF;	
	
	SELECT COUNT(*) 
		INTO v_count
			FROM USER_SEQUENCES WHERE SEQUENCE_NAME = v_sequence_cliente;
	
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE ' || v_sequence_cliente;
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_cliente || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_cliente || ' NAO EXISTE.');
	END IF;	
	
	SELECT COUNT(*) 
		INTO v_count
			FROM USER_SEQUENCES WHERE SEQUENCE_NAME = v_sequence_acessoria;
	
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE ' || v_sequence_acessoria;
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_acessoria || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('SEQUENCIA ' || v_sequence_acessoria || ' NAO EXISTE.');
	END IF;	
	
	SELECT COUNT(*) INTO v_count
		FROM ALL_TABLES WHERE TABLE_NAME = v_table_acessoria AND OWNER = v_owner;
		
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_table_acessoria || ' CASCADE CONSTRAINTS';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_table_acessoria || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABLEA ' || v_table_acessoria || ' NAO EXISTE.');
	END IF;		
		
	SELECT COUNT(*) INTO v_count
		FROM ALL_TABLES WHERE TABLE_NAME = v_table_endereco AND OWNER = v_owner;
		
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_table_endereco || ' CASCADE CONSTRAINTS';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_table_endereco || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABLEA ' || v_table_endereco || ' NAO EXISTE.');
	END IF;
	
	SELECT COUNT(*) INTO v_count
		FROM ALL_TABLES WHERE TABLE_NAME = v_table_cliente AND OWNER = v_owner;
		
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_table_cliente || ' CASCADE CONSTRAINTS';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_table_cliente || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABLEA ' || v_table_cliente || ' NAO EXISTE.');
	END IF;	
		
	SELECT COUNT(*) INTO v_count
		FROM ALL_TABLES WHERE TABLE_NAME = v_table_empregado AND OWNER = v_owner;
		
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_table_empregado || ' CASCADE CONSTRAINTS';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_table_empregado || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABLEA ' || v_table_empregado || ' NAO EXISTE.');
	END IF;
	
	SELECT COUNT(*) INTO v_count
		FROM ALL_TABLES WHERE TABLE_NAME = v_table_projeto AND OWNER = v_owner;
		
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_table_projeto || ' CASCADE CONSTRAINTS';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_table_projeto || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABLEA ' || v_table_projeto || ' NAO EXISTE.');
	END IF;
	
	SELECT COUNT(*) INTO v_count
		FROM ALL_TABLES WHERE TABLE_NAME = v_table_departamento AND OWNER =  v_owner;
		
	IF v_count = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_owner || '.' || v_table_departamento || ' CASCADE CONSTRAINTS';
		DBMS_OUTPUT.PUT_LINE('TABELA ' || v_table_departamento || ' EXCLUIDA COM SUCESSO.');
	ELSE
		DBMS_OUTPUT.PUT_LINE('TABLEA ' || v_table_departamento || ' NAO EXISTE.');
	END IF;
	
END;
/

CREATE SEQUENCE SEQUENCE_DEPARTAMENTO 
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQUENCE_PROJETO
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQUENCE_EMPREGADO
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQUENCE_CLIENTE
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQUENCE_ACESSORIA 
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE TABLE DEPARTAMENTO (
Codigo_Departamento NUMBER NOT NULL,
Nome_Departamento VARCHAR2(20) NOT NULL,
CONSTRAINT PK_CODIDO_DEPARTAMENTO PRIMARY KEY (Codigo_Departamento)
);

CREATE TABLE PROJETO (
Codigo_Projeto NUMBER NOT NULL,
Nome_Projeto VARCHAR2(20) NOT NULL,
Descricao_Projeto VARCHAR2(100),
Data_Inicio DATE,
Codigo_Departamento NUMBER NOT NULL,
CONSTRAINT PK_CODIDO_PROJETO PRIMARY KEY (Codigo_Projeto),
CONSTRAINT FK_PROJETO_COD_DEPTO FOREIGN KEY(Codigo_Departamento) REFERENCES DEPARTAMENTO (Codigo_Departamento)
);

CREATE TABLE EMPREGADO (
Codigo_Empregado NUMBER NOT NULL,
Nome_Empregado VARCHAR2(50) NOT NULL,
Cargo VARCHAR2(20),
Codigo_Projeto NUMBER NOT NULL,
CONSTRAINT PK_CODIGO_EMPREGADO PRIMARY KEY (Codigo_Empregado),
CONSTRAINT FK_EMP_COD_PROJ FOREIGN KEY(Codigo_Projeto) REFERENCES PROJETO (Codigo_Projeto)
);

CREATE TABLE CLIENTE (
Codigo_Cliente NUMBER NOT NULL,
Nome_Cliente VARCHAR2(20),
Telefone VARCHAR2(14),
CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (Codigo_Cliente)
);

CREATE  TABLE ENDERECO (
Codigo_Cliente NUMBER NOT NULL,
rua VARCHAR(100),
numero NUMBER,
bairro VARCHAR(100),
cidade VARCHAR(100),
estado CHAR(15),
cep VARCHAR(10),
complemento VARCHAR2(100),
CONSTRAINT PK_END_COD_CLI PRIMARY KEY (Codigo_Cliente),
CONSTRAINT fk_endereco_cod_cliente FOREIGN KEY (Codigo_Cliente)
REFERENCES cliente (Codigo_Cliente)
);

CREATE TABLE ACESSORIA (
Codigo_Acessoria NUMBER NOT NULL,
Codigo_Empregado NUMBER NOT NULL,
Codigo_Cliente NUMBER NOT NULL,
Data_Acessoria DATE,
Descricao_Acessoria VARCHAR2(100),
CONSTRAINT PK_CODIGO_ACESSORIA PRIMARY KEY (Codigo_Acessoria, Codigo_Empregado, Codigo_Cliente),
CONSTRAINT FK_ACESS_COD_EMP FOREIGN KEY(Codigo_Empregado) REFERENCES EMPREGADO (Codigo_Empregado),
CONSTRAINT FK_ACESS_COD_CLI FOREIGN KEY (Codigo_Cliente) REFERENCES CLIENTE (Codigo_Cliente)
);

INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,NOME_DEPARTAMENTO) VALUES (SEQUENCE_DEPARTAMENTO.NEXTVAL,'COMPRAS');

INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,NOME_DEPARTAMENTO) VALUES (SEQUENCE_DEPARTAMENTO.NEXTVAL,'VENDAS');

INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,NOME_DEPARTAMENTO) VALUES (SEQUENCE_DEPARTAMENTO.NEXTVAL,'INFORMÁTICA');

INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,NOME_DEPARTAMENTO) VALUES (SEQUENCE_DEPARTAMENTO.NEXTVAL,'MARKETING');

INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,NOME_DEPARTAMENTO) VALUES (SEQUENCE_DEPARTAMENTO.NEXTVAL,'SUPORT TI');

INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,NOME_DEPARTAMENTO) VALUES (SEQUENCE_DEPARTAMENTO.NEXTVAL,'ADMINISTRAÇÃO');

COMMIT;

INSERT INTO PROJETO (CODIGO_PROJETO,NOME_PROJETO,DESCRICAO_PROJETO,DATA_INICIO,CODIGO_DEPARTAMENTO) VALUES (
SEQUENCE_PROJETO.NEXTVAL,'REDUÇÃO DE CUSTOS','ANALISAR OS FORNECEDORES PARA REDUZIR O CUSTO DE COMPRA DOS PRODUTOS.','26-05-2007',1);

INSERT INTO PROJETO (CODIGO_PROJETO,NOME_PROJETO,DESCRICAO_PROJETO,DATA_INICIO,CODIGO_DEPARTAMENTO) VALUES (
SEQUENCE_PROJETO.NEXTVAL,'AUMENTO VENDAS','ELABORAR AÇÕES PARA AMPLIAR AS VENDAS JUNTO DOS CLIENTES.','06-09-2010',2);

INSERT INTO PROJETO (CODIGO_PROJETO,NOME_PROJETO,DESCRICAO_PROJETO,DATA_INICIO,CODIGO_DEPARTAMENTO) VALUES (
SEQUENCE_PROJETO.NEXTVAL,'WEB','MIGRAR O SISTEMA PARA WEB.','02-01-2011',3);

INSERT INTO PROJETO (CODIGO_PROJETO,NOME_PROJETO,DESCRICAO_PROJETO,DATA_INICIO,CODIGO_DEPARTAMENTO) VALUES (
SEQUENCE_PROJETO.NEXTVAL,'AMPLIAÇÃO DA REDE','AMPLIAÇÃO DA REDE PARA INCLUIR SETORES NÃO INFOMRATIZADOS.','10-03-2013',3);

INSERT INTO PROJETO (CODIGO_PROJETO,NOME_PROJETO,DESCRICAO_PROJETO,DATA_INICIO,CODIGO_DEPARTAMENTO) VALUES (
SEQUENCE_PROJETO.NEXTVAL,'REDE WIRELESS','ATUALIZAR A REDE WIRELESS PARA MELHORAR A TRANSMISSÃO DE DADOS.','23-11-2013',4);

COMMIT;

INSERT INTO EMPREGADO (CODIGO_EMPREGADO,NOME_EMPREGADO,CARGO,CODIGO_PROJETO) VALUES (
SEQUENCE_EMPREGADO.NEXTVAL,'MARIA SILVA','GERENTE',1);

INSERT INTO EMPREGADO (CODIGO_EMPREGADO,NOME_EMPREGADO,CARGO,CODIGO_PROJETO) VALUES (
SEQUENCE_EMPREGADO.NEXTVAL,'JOÃO BARBOSA','CONSULTOR',2);

INSERT INTO EMPREGADO (CODIGO_EMPREGADO,NOME_EMPREGADO,CARGO,CODIGO_PROJETO) VALUES (
SEQUENCE_EMPREGADO.NEXTVAL,'KARLA KAMURATI','ANALISTA',3);

INSERT INTO EMPREGADO (CODIGO_EMPREGADO,NOME_EMPREGADO,CARGO,CODIGO_PROJETO) VALUES (
SEQUENCE_EMPREGADO.NEXTVAL,'MATHES SAMPAIO','ANALISTA DE REDES',4);

INSERT INTO EMPREGADO (CODIGO_EMPREGADO,NOME_EMPREGADO,CARGO,CODIGO_PROJETO) VALUES (
SEQUENCE_EMPREGADO.NEXTVAL,'VALMOR BRITO','SUPORTE',5);

INSERT INTO EMPREGADO (CODIGO_EMPREGADO,NOME_EMPREGADO,CARGO,CODIGO_PROJETO) VALUES (
SEQUENCE_EMPREGADO.NEXTVAL,'ALEXANDRE FIGUEIREDO','SUPORTE',5);

COMMIT;

INSERT INTO CLIENTE (CODIGO_CLIENTE,NOME_CLIENTE,TELEFONE) VALUES (SEQUENCE_CLIENTE.NEXTVAL,'MANOEL FERREIRA','(41) 3344-5566');

INSERT INTO CLIENTE (CODIGO_CLIENTE,NOME_CLIENTE,TELEFONE) VALUES (SEQUENCE_CLIENTE.NEXTVAL,'WILLIAN QUEIROZ','(41) 3333-3333');

INSERT INTO CLIENTE (CODIGO_CLIENTE,NOME_CLIENTE,TELEFONE) VALUES (SEQUENCE_CLIENTE.NEXTVAL,'ANNA PADRÃO PADRÃO','(41) 3031-3233');

INSERT INTO CLIENTE (CODIGO_CLIENTE,NOME_CLIENTE,TELEFONE) VALUES (SEQUENCE_CLIENTE.NEXTVAL,'MARIANA SILVÉRIO','(41) 9876-0203');

COMMIT;

INSERT INTO ENDERECO (CODIGO_CLIENTE,RUA,NUMERO,BAIRRO,CEP,CIDADE,ESTADO,COMPLEMENTO) VALUES (
1,'RUA ABELARDO BARBOSA',21,'MOSSUNQUE','88.056-005','CURITIBA','PARANÁ','CASA');

INSERT INTO ENDERECO (CODIGO_CLIENTE,RUA,NUMERO,BAIRRO,CEP,CIDADE,ESTADO,COMPLEMENTO) VALUES (
2,'AV. BARÃO DO CERRO AZUL',485,'CENTRO','89.458-692','CURITIBA','PARANÁ','APTO. 32');

INSERT INTO ENDERECO (CODIGO_CLIENTE,RUA,NUMERO,BAIRRO,CEP,CIDADE,ESTADO,COMPLEMENTO) VALUES (
3,'RUA FRANCISCA ARAUJO',100,'JUVEVE','80.456-789','CURITIBA','PARANÁ','CASA Nº 3');

INSERT INTO ENDERECO (CODIGO_CLIENTE,RUA,NUMERO,BAIRRO,CEP,CIDADE,ESTADO,COMPLEMENTO) VALUES (
4,'RUA DAS AMOREIRAS',1478,'CABRAL','80.555-600','CURITIBA','PARANÁ','APTO. 304');

COMMIT;

INSERT INTO ACESSORIA (CODIGO_ACESSORIA,DATA_ACESSORIA,DESCRICAO_ACESSORIA,CODIGO_EMPREGADO,CODIGO_CLIENTE) VALUES (
SEQUENCE_ACESSORIA.NEXTVAL,'02-05-2010','SOLICITAR AS POLÍTICAS PARA A REDUÇÃO DE CUSTO DA EMPRESA.',1,1);

INSERT INTO ACESSORIA (CODIGO_ACESSORIA,DATA_ACESSORIA,DESCRICAO_ACESSORIA,CODIGO_EMPREGADO,CODIGO_CLIENTE) VALUES (
SEQUENCE_ACESSORIA.NEXTVAL,'06-06-2010','REALIZAR A INSCRIÇÃO PARA OFERTAR PROPOSTA DE INSENTIVO DE VENDAS.',2,2);

INSERT INTO ACESSORIA (CODIGO_ACESSORIA,DATA_ACESSORIA,DESCRICAO_ACESSORIA,CODIGO_EMPREGADO,CODIGO_CLIENTE) VALUES (
SEQUENCE_ACESSORIA.NEXTVAL,'08-08-2011','PROPOSTA DE SISTEMA PARA WEB.',3,3);

INSERT INTO ACESSORIA (CODIGO_ACESSORIA,DATA_ACESSORIA,DESCRICAO_ACESSORIA,CODIGO_EMPREGADO,CODIGO_CLIENTE) VALUES (
SEQUENCE_ACESSORIA.NEXTVAL,'22-09-2012','SOLICITAÇÃO DE CONEXÃO COM A REDE.',4,4);

INSERT INTO ACESSORIA (CODIGO_ACESSORIA,DATA_ACESSORIA,DESCRICAO_ACESSORIA,CODIGO_EMPREGADO,CODIGO_CLIENTE) VALUES (
SEQUENCE_ACESSORIA.NEXTVAL,'20-03-2013','ACESSORIA MUITO BOA.',5,1);

COMMIT;
